Rosbot xl snap (#23)
* foxglove layout fixes

* new motd

* fix simlinks

* disable auto-refresh for installed snaps

* Update netplan.yaml (#20)

* small fixes

* Update netplan.yaml in ROSbot XL config

* small fix for panther

* fix setup for ROSbot XL

---------

Co-authored-by: Rafal Gorecki <126687345+rafal-gorecki@users.noreply.github.com>

diff --git a/setup_robot_configuration b/setup_robot_configuration
--- a/setup_robot_configuration
+++ b/setup_robot_configuration
@@ -6,6 +6,10 @@ if [[ $EUID -ne 0 ]]; then
    exit 1
 fi
 
+echo "---------------------------------------"
+echo "Starting the configuration script"
+echo "---------------------------------------"
+
 # resize fs
 echo "Resizing the file system"
 
@@ -27,60 +31,114 @@ if [[ $# -gt 2 ]]; then
     exit 0
 fi
 
+# ========================================
+# Check ROS version
+# ========================================
+
 if [ -z "$2" ]; then
-  if [ "$IMAGE_TYPE" == "VULCANEXUS_HUMBLE" ]; then
-    ros_version="vulcanexus_humble"
-  elif [ "$IMAGE_TYPE" == "ROS2_JAZZY" ]; then
+  if [ "$IMAGE_TYPE" == "ROS2_JAZZY" ]; then
     ros_version="ros2_jazzy"
   elif [ "$IMAGE_TYPE" == "ROS2_HUMBLE" ]; then
     ros_version="ros2_humble"
   elif [ "$IMAGE_TYPE" == "ROS2_FOXY" ]; then
     ros_version="ros2_humble"
-  elif [ "$IMAGE_TYPE" == "ROS_NOETIC" ]; then
-    ros_version="ros_noetic"
   else
     echo "Error: No ROS version specified"
     exit 1
   fi
 else
-  if [ "$2" == "vulcanexus_humble" ] || [ "$2" == "ros2_jazzy" ] || [ "$2" == "ros2_humble" ] || [ "$2" == "ros_noetic" ]; then
-    ros_version="$2"
-  else
+  VALID_ROS_VERSIONS=("ros2_jazzy" "ros2_humble")
+
+  valid=false
+  for version in "${VALID_ROS_VERSIONS[@]}"; do
+    if [[ "$2" == "$version" ]]; then
+      valid=true
+      ros_version="$2"
+      break
+    fi
+  done
+
+  if ! $valid; then
     echo "Error: Invalid ROS version specified: $2"
     echo "Usage: $(basename "$0") ROBOT_MODEL ROS_VERSION"
+    echo "Valid ROS versions: ${VALID_ROS_VERSIONS[*]}"
     exit 1
   fi
 fi
 
 echo "ROS version: ${ros_version}"
 
+# ========================================
+# Check the robot model
+# ========================================
+
+# Get the directory where the script itself is located
+# SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)" # this one does not work with simlinks
+SCRIPT_DIR="$(cd "$(dirname "$(readlink -f "$0")")" && pwd)"
+
 if [ -z "$1" ]; then
   echo ""
   echo "Using default configuration"
   exit 0
 else
-  if [ "$1" == "rosbot_xl" ] || [ "$1" == "rosbot_3" ] || [ "$1" == "rosbot_2r" ] || [ "$1" == "rosbot_2_pro" ] || [ "$1" == "panther" ]; then
-    robot_model="$1"
-  else
+  VALID_ROBOT_MODELS=("rosbot_xl" "rosbot_3" "rosbot_2r" "rosbot_2_pro" "panther" "lynx")
+
+  valid=false
+  for model in "${VALID_ROBOT_MODELS[@]}"; do
+    if [[ "$1" == "$model" ]]; then
+      valid=true
+      robot_model="$1"
+      break
+    fi
+  done
+
+  if ! $valid; then
     echo "Error: Invalid robot model: $1"
     echo "Usage: $(basename "$0") ROBOT_MODEL ROS_VERSION"
+    echo "Valid robot models: ${VALID_ROBOT_MODELS[*]}"
     exit 1
   fi
 
   echo "Robot model: ${robot_model}"
 
-  cp -rp /etc/husarion/robot_configs/${robot_model}/${ros_version}/* /home/husarion
-  dpkg -i /etc/husarion/robot_configs/${robot_model}/motd_$(uname -m).deb
-  cp /etc/husarion/robot_configs/${robot_model}/netplan.yaml /etc/netplan/01-network-manager-all.yaml
-  bash /usr/lib/husarion/custom_config_${robot_model}.sh
+  [ -d $SCRIPT_DIR/robots/${robot_model}/${ros_version} ] && cp -rp $SCRIPT_DIR/robots/${robot_model}/${ros_version}/* /home/husarion
+  bash $SCRIPT_DIR/robots/${robot_model}/custom_config.sh
+
+  ## install motd
+  ARCH=$(uname -m)
+
+  # Map uname -m to .deb architecture
+  if [[ "$ARCH" == "x86_64" ]]; then
+    DEB_ARCH="amd64"
+  elif [[ "$ARCH" == "aarch64" ]]; then
+    DEB_ARCH="arm64"
+  else
+    echo "Unsupported architecture: $ARCH"
+    exit 1
+  fi
+
+  # Look for the matching .deb file using a regex pattern
+  DEB_FILE=$(find "$SCRIPT_DIR/robots/${robot_model}" -maxdepth 1 -type f -regex ".*husarion-motd-.*-${DEB_ARCH}\.deb" | head -n 1)
+
+  if [[ -z "$DEB_FILE" ]]; then
+    echo "Error: No matching .deb file found for architecture: $DEB_ARCH"
+    exit 1
+  fi
+
+  echo "Installing motd package: $DEB_FILE"
+  # Install the package
+  sudo dpkg -i "$DEB_FILE"
 fi
 
-mkdir /home/husarion/.ros
-chown husarion:husarion /home/husarion/.ros
+# mkdir /home/husarion/.ros
+# chown husarion:husarion /home/husarion/.ros
 
+echo "Resetting the network configuration"
+cp $SCRIPT_DIR/robots/${robot_model}/netplan.yaml /etc/netplan/01-network-manager-all.yaml
 sudo chmod 600 /etc/netplan/01-network-manager-all.yaml
 
 # Generating new SSH credentials
+echo "Generating new SSH credentials"
 sudo echo "" > /root/.ssh/authorized_keys
 sudo echo "" > /root/.ssh/known_hosts
 sudo echo "" > /home/husarion/.ssh/authorized_keys
